#! /bin/sh

# autostart
~/.config/bspwm/autostart.sh &

# workspaces
bspc monitor -d code web chat media other

# config
bspc config border_width         2
bspc config window_gap           12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# border colors
source ~/.cache/wal/colors.sh

bspc config normal_border_color  "$color08"
bspc config active_border_color  "$color08"

bspc config focused_border_color "$color13"

# rules
bspc rule -a Alacritty desktop='code' follow=on
bspc rule -a firefox   desktop='web'  center=on state=floating follow=on rectangle=1440x900+0+0

