#!/bin/sh

# autostart
~/.config/bspwm/autostart.sh &

# workspaces
bspc monitor -d I II III IV V VI

# config
bspc config border_width       2
bspc config window_gap         12
bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true

# border colors
bg=$(xrdb ~/.config/xorg/Xresources -query all | grep background | awk '{print $2}')
fg=$(xrdb ~/.config/xorg/Xresources -query all | grep foreground | awk '{print $2}')

bspc config active_border_color  "$bg"
bspc config normal_border_color  "$bg"

bspc config focused_border_color "$fg"

# window rules
bspc rule -a Alacritty desktop='^1'
bspc rule -a firefox   desktop='^2' state=floating follow=on

