#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -f ~/.config/xorg/Xresources ]; then
  xrdb -merge -I$HOME ~/.config/xorg/Xresources
fi

eval $(ssh-agent)

setxkbmap -model pc105 -layout de &
xsetroot -cursor_name left_ptr &

sh ~/.fehbg &

picom --experimental-backends &

sxhkd &
exec bspwm

